//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.Common.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.Common.Resource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nguyên giá.
        /// </summary>
        public static string NV_Cost {
            get {
                return ResourceManager.GetString("NV_Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã tài sản.
        /// </summary>
        public static string VN_AssetCode {
            get {
                return ResourceManager.GetString("VN_AssetCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tài sản .
        /// </summary>
        public static string VN_AssetName {
            get {
                return ResourceManager.GetString("VN_AssetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã đã tồn tại trong hệ thống.
        /// </summary>
        public static string VN_CodeExist {
            get {
                return ResourceManager.GetString("VN_CodeExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị hao mòn lũy kế.
        /// </summary>
        public static string VN_DepreciationValue {
            get {
                return ResourceManager.GetString("VN_DepreciationValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to không được phép để trống.
        /// </summary>
        public static string VN_EmptyCheck {
            get {
                return ResourceManager.GetString("VN_EmptyCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID đã tồn tại trong hệ thống.
        /// </summary>
        public static string VN_EmptyCheckIdExist {
            get {
                return ResourceManager.GetString("VN_EmptyCheckIdExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra vui lòng liên hệ MISA.
        /// </summary>
        public static string VN_ErrorSystem {
            get {
                return ResourceManager.GetString("VN_ErrorSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tệp không tồn tại.
        /// </summary>
        public static string VN_FileExist {
            get {
                return ResourceManager.GetString("VN_FileExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tệp không đúng định dạng.
        /// </summary>
        public static string VN_FileNotFormat {
            get {
                return ResourceManager.GetString("VN_FileNotFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu đầu vào không hợp lệ.
        /// </summary>
        public static string VN_InvalidInput {
            get {
                return ResourceManager.GetString("VN_InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to đã tồn tại trong hệ thống ?.
        /// </summary>
        public static string VN_SameCode {
            get {
                return ResourceManager.GetString("VN_SameCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to không đúng định dạng.
        /// </summary>
        public static string VN_VaildateFormat {
            get {
                return ResourceManager.GetString("VN_VaildateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nguyên giá phải lớn hơn giá trị hao mòn năm.
        /// </summary>
        public static string VN_ValueCost {
            get {
                return ResourceManager.GetString("VN_ValueCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu đầu vào không đúng kiểu.
        /// </summary>
        public static string VN_ValueNotType {
            get {
                return ResourceManager.GetString("VN_ValueNotType", resourceCulture);
            }
        }
    }
}
